/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import swingsample.*;
import java.awt.event.MouseEvent;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUC-PC
 */
class BOARD {

    public enum STATE {
        X, O, N
    };
    int x;
    int y;
    STATE state;

    public BOARD(int x, int y, STATE state) {
        this.x = x;
        this.y = y;
        this.state = state;
    }
}

public final class NewJFrameaaa extends javax.swing.JFrame {

    private final int COL = 20;
    private BOARD[][] boardses = new BOARD[COL][COL];
    
    private BOARD.STATE current = BOARD.STATE.N;
    
    private final Object[][] cells = new Object[COL][COL];
    private final String[] cols = new String[COL];

    /**
     * Creates new form NewJFrame
     */
    public NewJFrameaaa() {
        initComponents();

        // init model
        DefaultTableModel dm = new DefaultTableModel();    
        for (int i = 0; i < COL; i++) {
            cols[i] = i+"";
        }
        dm.setDataVector(cells, cols);
        jTable1.setModel(dm);
      
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
//            jTable1.getColumn(i+"").setCellRenderer(new ButtonRenderer());
            jTable1.getColumn(i+"").setCellEditor(new ButtonEditor(new JCheckBox()));
        }
        
 
        setCellsAlignment(jTable1, SwingConstants.CENTER);
        for (int i = 0; i < COL; i++) {
            //BOARD[] boardse = boardses[i];
            for (int j = 0; j < COL; j++) {
                boardses[i][j] = new BOARD(i, j, BOARD.STATE.N);
            }
        }

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2 || evt.getButton() == MouseEvent.BUTTON3) {

                    int row = jTable1.rowAtPoint(evt.getPoint());
                    int col = jTable1.columnAtPoint(evt.getPoint());
                    if (row >= 0 && col >= 0) {
                        BOARD boar = boardses[row][col];

                        if (current != BOARD.STATE.N) {
                            if (boar.state == BOARD.STATE.N) {
                                String state = "0";
                                if (current == BOARD.STATE.O) {
                                    current = BOARD.STATE.X;
                                    state = "X";
                                } else {
                                    current = BOARD.STATE.O;
                                }
                                boar.state = current;
                                jTable1.getModel().setValueAt(state, row, col);

                            }
                        }
                        jTable1.getColumnModel().getSelectionModel().clearSelection();
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        getContentPane().add(jTable1);
        jTable1.setBounds(50, 10, 500, 500);

        jPanel1.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("X");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(6, 5, 31, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("O");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(42, 5, 33, 23);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(10, 40, 73, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(560, 30, 160, 170);

        setBounds(0, 0, 770, 569);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            current = BOARD.STATE.X;
        } else {
            current = BOARD.STATE.O;
        }
        jPanel1.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed
    public void setCellsAlignment(JTable table, int alignment) {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(alignment);

        TableModel tableModel = table.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
            table.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrameaaa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
