/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingsample;

import javax.swing.JOptionPane;
import swingsample.control.IFCellType;

/**
 *
 * @author ASUC-PC
 */
public class NewJFrame1 extends javax.swing.JFrame {

    public static CellType cellState = CellType.O;

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        inititla();
    }

    private void inititla() {
        table = LogicBoard.createBoard(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInfo = new javax.swing.ButtonGroup();
        table = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnAction = new javax.swing.JButton();
        buttonO1 = new swingsample.control.ButtonO();
        buttonX1 = new swingsample.control.ButtonX();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setEnabled(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowSelectionAllowed(false);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        getContentPane().add(table);
        table.setBounds(220, 20, 700, 700);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 10, 2, 2);

        btnAction.setText("Start");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction);
        btnAction.setBounds(30, 30, 130, 30);

        buttonGroupInfo.add(buttonO1);
        buttonO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonO1);
        buttonO1.setBounds(30, 80, 75, 75);

        buttonGroupInfo.add(buttonX1);
        buttonX1.setSelected(true);
        buttonX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonX1);
        buttonX1.setBounds(30, 170, 75, 75);

        setBounds(0, 0, 1060, 781);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRadioActionPerformed
        // TODO add your handling code here:
        IFCellType cell = (IFCellType) evt.getSource();
        cellState = cell.getCellType();
    }//GEN-LAST:event_buttonRadioActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
        if (!Common.isStart) {
            Common.isStart = true;

            btnAction.setText("New game");
        } else {
            boolean isNew = true;
            if (!Common.isWin) {
                if (JOptionPane.showConfirmDialog(this, "Are you sure?", "Confim", JOptionPane.OK_CANCEL_OPTION, WIDTH) != JOptionPane.OK_OPTION) {
                    isNew = false;
                }
            }
            if (isNew) {
                btnAction.setText("Start");
                Common.clearToNew();
                inititla();
            }
        }
        this.table.setEnabled(Common.isStart);
        buttonO1.setEnabled(!Common.isStart);
        buttonX1.setEnabled(!Common.isStart);
    }//GEN-LAST:event_btnActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.ButtonGroup buttonGroupInfo;
    private swingsample.control.ButtonO buttonO1;
    private swingsample.control.ButtonX buttonX1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
